### ISSUE TITLE
Should we use Preact ?

### ISSUE THREAD

**Issue by gaboesquivel** [puravidadac/dmeetup#9]
I definitively don't want to optimize prematuraly, however I think it's worth it to consider Preact for this project. What would be downsides of using it ?

**Comment by andrralv** [comment]
Hi! I'm interested in helping out in the project every once in a while. I don't find any problems in using preact instead of vanilla react. My only concern is using Redux (I haven't used/don't know how reliable this is: https://www.npmjs.com/package/preact-redux). 

Or we could just try staying with Context API.

**Comment by gaboesquivel** [comment]
@andrralv thanks!  @kevinwolfcr  what do you think?

**Comment by gaboesquivel** [comment]
unnecessary
